logging:
  pattern:
    dateformat: HH:mm:ss:SSS
  level:
    cn.itcast: debug
spring:
  rabbitmq:
    # 单机模式
    host: 91.199.209.120 # rabbitMQ的ip地址
    port: 5672 # 端口

    # 多机模式
    # addresses: 127.0.0.1:8071, 127.0.0.1:8072, 127.0.0.1:8073
    username: itcast
    password: 123321
    virtual-host: /
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: auto # none在消费端未正常处理会丢失；auto自动进入消费者通道，客户端挂掉，仍然会丢失通道内的消息，需要manual处理.
        retry:
          enabled: true
          initial-interval: 1000 # 单位ms
          multiplier: 3
          max-attempts: 4 # 重试次数4,实际上第一次也算在里面，相当于第一次失败后重试了三次,合计运行了4次。
