# 启动三个并不是集群，还需要进入redis手动设置.
# slaveof:设置为某192.168.150.101 7001从。
# replicaof 192.168.150.101 7001

version: "3.9"
services:
  redis1:
    container_name: redis1
    image: redis:7.0.4-alpine3.16
    volumes:
      - /usr/local/etc/redisContain/redis1/conf:/usr/local/etc/redis
      - /usr/local/etc/redisContain/redis1/logs/redis.log:/data/logs/redis.log
      - /usr/local/etc/redisContain/redis1/data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "7001:6379"
  redis2:
    container_name: redis2
    image: redis:7.0.4-alpine3.16
    volumes:
      - /usr/local/etc/redisContain/redis2/conf:/usr/local/etc/redis
      - /usr/local/etc/redisContain/redis2/logs/redis.log:/data/logs/redis.log
      - /usr/local/etc/redisContain/redis2/data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "7002:6379"
  redis3:
    container_name: redis3
    image: redis:7.0.4-alpine3.16
    volumes:
      - /usr/local/etc/redisContain/redis3/conf:/usr/local/etc/redis
      - /usr/local/etc/redisContain/redis3/logs/redis.log:/data/logs/redis.log
      - /usr/local/etc/redisContain/redis3/data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "7003:6379"
