# docker-compose.yml
version: "3.9"
services:
  redis1:
    container_name: redis1
    image: redis:7.0.4-alpine3.16
    volumes:
      - /usr/local/etc/redisContain/redis1/conf:/usr/local/etc/redis
      - /usr/local/etc/redisContain/redis1/logs/redis.log:/data/logs/redis.log
      - /usr/local/etc/redisContain/redis1/data:/data
    command: 
      redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"

